name: S3 CI/CD

on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: "Choose Action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform-s3:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-s3

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform-s3

      - name: Terraform Apply
        if: ${{ github.event.inputs.ACTION == 'apply' }}
        run: terraform apply -auto-approve
        working-directory: terraform-s3

      - name: Terraform Destroy
        if: ${{ github.event.inputs.ACTION == 'destroy' }}
        run: terraform destroy -auto-approve
        working-directory: terraform-s3

      - name: Show Outputs
        if: github.event.inputs.ACTION == 'apply'
        run: terraform output
        working-directory: terraform-s3

      - name: Cleanup Workspace
        if: always()
        run: |
          echo "Cleaning workspace..."
          rm -rf *
          echo "Workspace cleaned ✅"
